### ISSUE TITLE
Latest version of gSDK?

### ISSUE THREAD

**Issue by vaibhavviswanathan** [Flova/ros_gremsy#5]
Is ros_gremsy compatible with the latest version of gSDK?

**Comment by Flova** [comment]
Oh, I didn't noticed that the repo was moved and updated. I will have a look at it in the following days. Thanks for reminding me.

**Comment by Flova** [comment]
I bumped it to the newest version and tested it with our gimbal and everything seems to work fine. If you have any issues let me know.
