### ISSUE TITLE
ROS releases and py2/py3

### ISSUE THREAD

**Issue by roboticlemon** [Flova/ros_gremsy#7]
Should put a note that this repo by default only works with Noetic by default because of the python3 shebang in the[ dynamic reconfigure cfg](https://github.com/Flova/ros_gremsy/blob/edb581bf6d002d9cd3bbe138ce9e70ac97b1a27a/cfg/ROSGremsy.cfg#L1): 
`#!/usr/bin/env python3`

Of course to run it pre-noetic you just remove the 3 from the shebang.

If we want this repo (and its subpackages) to build on the ros build farm you may want to consider making separate branches for each ros reversion like melodic-devel and noetic-devel.

**Comment by Flova** [comment]
Oh, thanks for noticing that. I currently use noetic or a python3 modified melodic and therefore didn't noticed it.

**Comment by Flova** [comment]
I created different branches for melodic and noetic
